# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'weixin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import ctypes
ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID("myappid")#解决任务栏图标问题，不知道原理


class Ui_Form(object):

    def __init__(self, Form):
        Form.setObjectName("Form")
        # Form.setWindowTitle("微信订阅号监控") 不起作用
        Form.setWindowIcon(QIcon("./pic/logo.ico"))
        Form.resize(1000, 501)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(40, 10, 121, 41))
        self.pushButton.setObjectName("pushButton")

        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(30, 70, 221, 401))
        self.textEdit.setObjectName("textBrowser")
        self.textEdit.setReadOnly(True)

        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(270, 70, 701, 401))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        # self.tableWidget.setRowCount(0)
        self.tableWidget.setHorizontalHeaderLabels(['公众号名称', '标题', '时间', '查看'])
        # self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        # self.tableWidget.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeToContents)
        self.tableWidget.setColumnWidth(0, 81)
        self.tableWidget.setColumnWidth(1, 340)
        self.tableWidget.setColumnWidth(2, 179)
        self.tableWidget.setColumnWidth(3, 100)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "启动微信监控"))
